### ISSUE TITLE
np.interp is not working for OpenRocket Cd data

### ISSUE THREAD

**Issue by thereal-adubs** [NUSTARS/ADS#2]
For interpolate_cd_openrocket(), the goal is to read in data and then use it to interpolate a Cd value for any Re even if it is not explicitly defined in the OpenRocket csv data set. 

np.interp is not working. 

After Re = 600,000 it begins to produce a flat line. I have temporarily solved this by using a high-degree polynomial. I would love to know why a linear interpolation does not work.

**Comment by Tara-s1** [comment]
it is fixed now. np.interp requires monotonically increasing x-coordinates which is messed up when you have random 0s in your dataset but you can fix it by forcing it to sort by specifying a period -- in this case, the period is np.inf since its not periodic data
